### ISSUE TITLE
List all categories

### ISSUE THREAD

**Issue by ivopanjos** [Shopkit/docs#1]
Why is not possible to list all categories?
It could be done similar to list all orders (/order - without any other parameter), and it would provide an easy way to know all the categories that are available, instead of having to iterate all products.

**Comment by davidaniel** [comment]
It's possible to list all categories (/category). Check our [documentation](https://shopk.it/developers/api#categories)

**Comment by ivopanjos** [comment]
Oh ok, that is awesome to know. But your documentation is not very explicit.
[https://shopk.it/developers/api#categories-get-category](url)

Since you have in the link: /category/{id,handle} in contrast with the order or products: /order{?id,,...}

Also in the URI Parameters:
In category: id integer (required), handle string (required), in contrast with:
In order : id integer (optional)

**Comment by davidaniel** [comment]
Nice catch. Thanks for pointing that.
