### ISSUE TITLE
Update product

### ISSUE THREAD

**Issue by rtmrodrigues** [Shopkit/docs#2]
Hi.

I'm trying to update the title of a product on a .NET program but it always return error 404.
I am able to get the product by ID into one .NET Object, change the title on the .NET Object but it does not update after webrequest.

Is there any other documentation with examples? Can you provide a .NET example?

Thank you.

**Comment by andrefrcastro** [comment]
Hi,

As of today the product API is read only. 
PUT/POST methods are in the works and we hope to release them soon.
