### ISSUE TITLE
PUT product update - seting  atributes to default

### ISSUE THREAD

**Issue by jorge-ribamar** [Shopkit/docs#3]
Once making a PUT request to change the 'new' field of a product, many atributes of the product changes.

I want to change only the 'new' field from True to False, and also is_promotion and stock_show turns false - not sure if any other as this where the only ones set as True in the product In was testing with.

The method should change just the fields contained in the request call.

**Comment by davidaniel** [comment]
@jorge-ribamar Thanks for pointing this out. Fixed.

**Comment by jorge-ribamar** [comment]
@davidaniel thanks a lot
