### ISSUE TITLE
PUT product - impossible to delete price_promo

### ISSUE THREAD

**Issue by jorge-ribamar** [Shopkit/docs#4]
Once set, it is impossible to delete price_promo from the app.
I'm setting is_promotion to False, price_promo = '' or price_promo = None and  'promo_show_percentage': False

Still price promo stays the same.
This causes two big issues:

- Even it is not a promotion, in the shop it will be shown as a promotion
- If later on the price changes, this will be causing issues. In case price drops, the API will not accept the new price; in case it raises, the shop will show the older discount price.

Here is the Json i put to the API
{'is_promotion': False,
 'price': 165.0,
 'price_promo': '',
 'promo_show_percentage': False,
 'status': 1,
 'stock_backorder': False,
 'stock_enabled': True,
 'stock_qty': 1,
 'stock_show': True}

Please let me know how I can set 'price_promo' to None.
Thanks in advance

**Comment by davidaniel** [comment]
Couple of improvements were made to api `/products`, this now should work as intended.
That is the correct way to remove a `price_promo`

 ```
{
    "price_promo": ""
}
```
