### ISSUE TITLE
Improvement - get product id on product creation

### ISSUE THREAD

**Issue by jorge-ribamar** [Shopkit/docs#5]
I am storing the product info to a DB.

Now I must creeate the product, then get the product, just to get the id to store in the DB.
I get it, but I am making more calls to the API - that could be avoided.

If this can be done, would be great.

**Comment by davidaniel** [comment]
That is what happens.
POST /product, returns de created product.

**Comment by jorge-ribamar** [comment]
Sorry, it does. I missed it
Thanks a lot
