### ISSUE TITLE
Wrong Themes documentation of product.options and product.option_groups.options

### ISSUE THREAD

**Issue by pcmind** [Shopkit/docs#6]
[theames.md](https://github.com/Shopkit/docs/blob/544e04d00dff30f1fc3b8291386c6142a692dac4/themes/docs/themes.md) documentation is wrong regarding "product.options".

The "Product" field named "product.options" is stated to be an array of all variants combined. Is is true but it miss to inform that it is a Array of "product.options".

The "product.option_groups" field named "product.option_groups.options" does not return a Array of "product.options" as stated but an array of an objects with only two field: id, title. And the id returned is not even related to the product.options.id.

It would be great to have an improved documentation on own the product.options are related to product.option_groups.options.

**Comment by davidaniel** [comment]
Thanks, that was a typo, we updated the docs.

`product.option_groups`, lists the product option groups (variants) ex: `Size[S,M,L], Color[Red,Blue]`
`product.option`, lists all option groups (variants) combined `[S/Red],[M/Red],[L/red]`
