### ISSUE TITLE
POST product - impossible to know brand identifier to send

### ISSUE THREAD

**Issue by tiagoalberto** [Shopkit/docs#7]
When creating new products, there is no endpoint to get brand identifier by name, so we can fill brand field accordingly.

**Comment by acdanielgomes** [comment]
Hi @tiagoalberto 
Thank you for pointing that
We are currently working to make the brand module available via API. As soon as it's publicly available, we'll let you know.

**Comment by acdanielgomes** [comment]
@tiagoalberto,
Brand module just get launched in the API. 
Take a look in the documentation [here](https://shopk.it/developers/api#brands) to see the available methods.

**Comment by tiagoalberto** [comment]
> @tiagoalberto, Brand module just get launched in the API. Take a look in the documentation [here](https://shopk.it/developers/api#brands) to see the available methods.

Great news :-)
